### ISSUE TITLE
[Feature Request] Option to disable php syntax checking

### ISSUE THREAD

**Issue by jhoff** [shufo/blade-formatter#691]
## Context (Environment)

We use the [Laravel Blade Filters](https://github.com/conedevelopment/blade-filters) package, which adds non-php syntax to blade expressions which is then compiled into valid php in the cached view file. It seems this formatter assumes that blade expressions should always contain valid php through the [prettier/plugin-php](https://github.com/prettier/plugin-php) package.

## Current Behavior

Blade expressions are always checked for php syntax

## Expected Behavior

It would be nice if there's an option to disable this syntax check

**Comment by shufo** [comment]
@jhoff 
Thanks for telling me that use case.

I agree with the requested option to resolve this issue.
Currently the default behavior is to perform a syntax check, so the only way to avoid this problem is to implement same compiler of [Laravel Blade Filters](https://github.com/conedevelopment/blade-filters) or suppress syntax errors completely or disabling format like: 

```blade
{{-- blade-formatter-disable-next-line --}}
{{ 'john' | ucfirst }} 
```

`.bladeignore`

```ignore
resources/views/filename
```

I'd like to implement this at some point.

**Comment by shufo** [comment]
Introduced at v1.30.0

https://github.com/shufo/blade-formatter/releases/tag/v1.30.0
